### ISSUE TITLE
Changing channel of a license give a "license update" version change, but does not pull new releases from channel

### ISSUE THREAD

**Issue by austinchambers** [replicatedhq/kots#624] opened 2020-06-01 22:03 UTC
This was previously reported as "fixed" and released in 1.12. The belief is that there was a regression that introduced then. 

This was an existing cluster, but I'm pretty sure this will be the same in embedded.

### Repro Steps

- vendor web: create a release on channel "refs/heads/master"
- vendor web: create a customer on channel
- kots: Do full install, get app running
- vendor web: create a release on channel "refs/heads/config-migrate"
- vendor web: switch customer channel to "refs/heads/config-migrate"
- kots: sync license, click "check for updates"

### Expected behavior
- able to pull latest release from the new channel in kots

### Actual behavior
- see "license sync" update event, but unable to pull latest release, "check for updates" does nothing -- maybe because the release on the new channel has a lower channel sequence?

**Comment by divolgin** [comment] 2020-07-08 15:45
@austinchambers after synching license you also have to click `Check for updates`.  This works as intended.

**Comment by austinchambers** [comment] 2020-07-16 16:45
@divolgin Check for updates was performed in the steps above. After clicking "check for updates," nothing happened.

**Comment by salahalsaleh** [comment] 2020-07-16 20:08
Thanks @austinchambers. This seems to be fixed in the latest release.

**Closed** 2020-07-16 20:08 UTC
