### ISSUE TITLE
Getting 403 from Cloud Flare when running kots install

### ISSUE THREAD

**Issue by namgk** [replicatedhq/kots#3164] opened 2022-09-13 17:25 UTC
Hi there,

We're running kots in our CI and during the installation step:

```
kubectl kots install 
```

we got 

```
Error: failed to validate installation: failed to get latest license: unexpected result from get request: 403
...
<div id="challenge-body-text" class="core-msg spacer">
  replicated.app needs to review the security of your connection before proceeding.
</div>
```

It used to work before.

Any idea?

Thanks

**Comment by sgalsaleh** [comment] 2022-09-29 18:35
can you please share the full install command? i'm not hitting this issue from my end. would you be able to share the license you're testing with so that i can try to reproduce?

**Comment by sgalsaleh** [comment] 2022-09-29 18:36
it might be because the license is archived. could you check if that's the case? you can check the from the vendor portal.

**Comment by namgk** [comment] 2022-09-29 18:44
we don't see it anymore, but your note makes sense, under what condition a license is archived?

**Comment by sgalsaleh** [comment] 2022-09-29 18:51
you'd control that from your end from the vendor portal. you have the ability to archive licenses.

**Comment by sgalsaleh** [comment] 2022-09-29 18:51
since you're not seeing it anymore, i'll close this issue for now. thank you.

**Closed by sgalsaleh** 2022-09-29 18:51 UTC
